language: node_js
node_js: - '6'
before_install: if [[ 6.13.6 != 3* ]]; then npm i -g npm@3; fi

cache:  directories:    - node_modules

sudo: false

addons:
    sonarcloud:
      organization: "sonar" # the key of the org you chose at step #3
      token:
        secure: "NFqVRJpWy7bfZsGjdTD+prYLcC8Rp9HJqlHGQCwb6/7AKMaux7EdxU1euN15u8xEBa0/bq9jSsxKyLm+TYHLFzRhgLesW0e+V29hv/oXzvlKIpyNg6yqDCmmHHA3UcUKBQmy1S4wxm7J26zqiNvFT4FcfT4bzpzuLT8gYOsWWfj8NhFSNKws3UaVFM8xqCSSAbUPY3jGmkKl1PNyUbHB6X3z1lEsXz6bgHTN+2BxaZl6XwxN5q+uctUNp/OHYhLphxOPLBtYTmndoCP56uxe9MVQA0u8xG0lHusfmsXqzB7xBa9smYLHqIBz168n9h65DfVgsdkVyDvjLHvQuVqKi/gcEGC4gQFzRpsoNtYuqZrffY969wkuAr80LxSiyWxXTplALBcNQD2BNrQX8Kf1CkTJydFaXyeyhBC91T3UQ3afmkhj19R2TQkKDToTz7CO3Ytm8dkbRVDEuzBW8aLM5T3fKq8iUDmDIfAkSyKRS/oGsIys6tYITu4bR3FkLzNkUg75VUN9bCrpxcM53QVwU3bHTR7KflOyKi2zWoM0ssxuOIZiQB5e1Q3smgLvPEi2xAlHq9issWawUdlSrxE2E68wNs/O5ZSe+Q7Ojrq/S4aqS+lux5NWLU49JJFUnRuSunGkQd1G0kAWcslonH9zGj7KE9QYOASxRKlMhDL1fKg="
  script:
    # other script steps might be done before running the actual analysis
    - sonar-scanner
