language: node_js

node_js:
  - "stable"

before_install:
  - npm install -g web-ext
  
script:
  - web-ext lint
  - web-ext build
  - sonar-scanner

addons:
  sonarcloud:
    organization: "persona"
    token: 
      secure: "TBSKYs9ews0DZljtdD/kjY2C/xqTISoFJDlA+bjm8F0iEcw8AllfimxSvVc+NCfwayrvAueWeVZzJSkBbCuqU+eQjnLnyKnjrkS2amlPDDHlvYc7ETukDJFTIGg2X77r6iHtzd3jwW6Ks0mr/LXTbl8iscsY1VrwtSB7eLY9GRQj0dQ9CY21PXscB6u0eSwzRTThCjiMQmEgJJ4uM5+zyjr57An96DVQS1a+L+urDkNi5wF55Ran2R3M0MazgrvifMvMD10FswbaJWd1QORYartcFpA5FicSK87S3wI9Xsxe7hncUiUWcBPmpOKz8ApLimUgBa3GHpH6GbmzasprYpS88sLwy5Roveh1LL1dUKoDNQn/tKS69DVEB+P/Hx79wOhRnYE2IHbiO4y/Ez2ZFuBwc+h1ja4974RWugro5PSkq9fOyq2tLOBPhbSvvIrtfmbI75D4wY4d7bRuqDhI/YYM1E2Rpr20vIB/kz+MokoojmlsbDbeNuj995BIsQlUd4k0uQ9TNhHa41zcgjSH3QoQPmZ0FqRNrvfeheCHzcrxBRBzGVEdp+tK5k4+D9xZk1Nz0xFpmDxomUxZhbdBz5G/z2CAeCmhnJA4hLo0Ogu0evh+XQUQAkMvE+IIVP64WeReGpP2gbteF6uSwB7H5GEhQ4AB8nvlxOH4YiI3UDg="
