dist: trusty
language: node_js
node_js:
  - "stable"

before_install:
  - npm install -g web-ext

addons:
  sonarcloud:
    organization: "persona"
    token: $SONAR_TOKEN

script:
    - web-ext lint
    - sonar-scanner
