dist: trusty
language: node_js
node_js:
  - "stable"

before_install:
  - npm install -g web-ext

addons:
  sonarcloud:
    organization: "persona"
    token: $SONAR_TOKEN
jobs:
  include:
  - stage: "Run Tests and SonarCloud Analysis"
    script:
    - npm test
    - web-ext lint
    - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY