dist: trusty
language: node_js

node_js:
  - "stable"


addons:
  sonarcloud:
    organization: "persona"
    token: $SONAR_TOKEN

before_install:
  - npm install -g web-ext
  
script:
  - web-ext lint
  - web-ext build
  - sonar-scanner
  
  