<<<<<<< HEAD
language: node_js

node_js:

  - "6"



script:

  - npm run lint

  - npm run build

  - npm test
=======

language: node_js
node_js: - '6'
before_install: if [[ 6.13.6 != 3* ]]; then npm i -g npm@3; fi

cache:  directories:    - node_modules

sudo: false


>>>>>>> d5a40776050cccc6a1814d900e5fb4083e6e13a6
